### ISSUE TITLE
Link to CU protocol incorrect

### ISSUE THREAD

**Issue by niels-sterrenburg** [tkem/CarreraDigitalControlUnit#8]
New link location:
http://slotbaer.de/carrera-digital-124-132/9-cu-daten-protokoll.html

Thanks for the good work !!

Niels

**Comment by tkem** [comment]
Thanks!

**Comment by tkem** [comment]
Fixed.

**Comment by niels-sterrenburg** [comment]
Hi Thomas,

I got some of your examples working and can successfully read items from
the track on the arduino nano.

I don't understand yet why not all examples work but I'll let you know
after further debugging.

I was wondering how to send control packets to the cu.

When i read
http://slotbaer.de/carrera-digital-124-132/9-cu-daten-protokoll.html
I see that there should be a possibility but I am unsure how to drive the
line down from the arduino.

Did you already experiment with writing commands to the cars or cu from the
arduino ?

Practical ideas:
- set speed of all the cars identical before starting
- stop the track when a number of laps is achieved
- record a round and relay it to a smarter ghost car which slows down and
accelerates for corners
- sky is the limit ;-)

Vielen Dank,

Niels Sterrenburg

Op wo 9 dec. 2020 09:10 schreef Thomas Kemmer <notifications@github.com>:
